import type { BootstrapState } from './protocol.js';

const managed = {
  mode: 'managed' as const,
  searchableByServer: true,
  appsMayReadContent: false,
  deletedContentRecoveryDays: 7,
  evidenceRetentionDays: 90,
};

const sealed = {
  mode: 'sealed' as const,
  searchableByServer: false,
  appsMayReadContent: false,
  deletedContentRecoveryDays: 0,
  evidenceRetentionDays: 0,
};

export const demoBootstrap: BootstrapState = {
  account: {
    id: 'account-you',
    handle: 'nightshift',
    displayName: 'Nightshift',
    initials: 'NS',
    status: 'online',
  },
  communities: [
    { id: 'community-ember', name: 'Ember Party', mark: 'EP', accent: '#ff7759', memberCount: 18 },
    { id: 'community-orbit', name: 'Orbit League', mark: 'OL', accent: '#6f8cff', memberCount: 42 },
    { id: 'community-forge', name: 'Forge Lab', mark: 'FL', accent: '#52c6a3', memberCount: 11 },
  ],
  activeCommunityId: 'community-ember',
  activeChannelId: 'channel-campfire',
  channels: [
    {
      id: 'channel-campfire',
      communityId: 'community-ember',
      name: 'campfire',
      kind: 'text',
      category: 'Hangout',
      topic: 'Plans, clips, and the running conversation.',
      privacy: managed,
      participants: [],
    },
    {
      id: 'channel-loadouts',
      communityId: 'community-ember',
      name: 'loadouts',
      kind: 'text',
      category: 'Hangout',
      topic: 'Builds and strategy without the scrollback noise.',
      privacy: managed,
      participants: [],
    },
    {
      id: 'channel-backstage',
      communityId: 'community-ember',
      name: 'backstage',
      kind: 'text',
      category: 'Private',
      topic: 'A sealed room. Only participating devices hold content keys.',
      privacy: sealed,
      participants: [],
    },
    {
      id: 'voice-ready-room',
      communityId: 'community-ember',
      name: 'Ready Room',
      kind: 'voice',
      category: 'Voice',
      topic: 'Drop in when you are ready to queue.',
      privacy: sealed,
      participants: [
        { id: 'account-mara', displayName: 'Mara', initials: 'MA', status: 'online' },
        { id: 'account-jules', displayName: 'Jules', initials: 'JU', status: 'online' },
        { id: 'account-ren', displayName: 'Ren', initials: 'RE', status: 'idle' },
      ],
    },
    {
      id: 'voice-late-lobby',
      communityId: 'community-ember',
      name: 'Late Lobby',
      kind: 'voice',
      category: 'Voice',
      topic: 'Low-key voice after the main group signs off.',
      privacy: sealed,
      participants: [],
    },
    {
      id: 'voice-stage-main',
      communityId: 'community-ember',
      name: 'Main Stage',
      kind: 'stage',
      category: 'Voice',
      topic: 'Broadcast channel — audio flows down to subchannels.',
      privacy: sealed,
      stageConfig: { broadcastKeybind: 'Ctrl+Shift+V' },
      participants: [{ id: 'account-mara', displayName: 'Mara', initials: 'MA', status: 'online' }],
    },
    {
      id: 'voice-stage-squad-alpha',
      communityId: 'community-ember',
      name: 'Squad Alpha',
      kind: 'voice',
      category: 'Voice',
      topic: 'Subchannel under Main Stage. Hears stage audio; does not broadcast back.',
      privacy: sealed,
      parentChannelId: 'voice-stage-main',
      participants: [
        { id: 'account-jules', displayName: 'Jules', initials: 'JU', status: 'online' },
        { id: 'account-ren', displayName: 'Ren', initials: 'RE', status: 'idle' },
      ],
    },
    {
      id: 'voice-stage-squad-bravo',
      communityId: 'community-ember',
      name: 'Squad Bravo',
      kind: 'voice',
      category: 'Voice',
      topic: 'Subchannel under Main Stage. Hears stage audio; does not broadcast back.',
      privacy: sealed,
      parentChannelId: 'voice-stage-main',
      participants: [],
    },
  ],
  messages: [
    {
      id: 'message-1',
      channelId: 'channel-campfire',
      author: { id: 'account-mara', displayName: 'Mara', initials: 'MA', status: 'online' },
      availability: 'plaintext',
      content: 'I moved the practice run to 8:30. No event maze—just show up in the Ready Room.',
      createdAt: '2026-06-29T19:12:00.000Z',
      editedAt: null,
      reactions: [{ emoji: '✓', count: 4, reacted: true }],
      attachments: [],
    },
    {
      id: 'message-2',
      channelId: 'channel-campfire',
      author: { id: 'account-jules', displayName: 'Jules', initials: 'JU', status: 'online' },
      availability: 'plaintext',
      content: 'Perfect. I will test the new capture settings before everyone joins.',
      createdAt: '2026-06-29T19:18:00.000Z',
      editedAt: null,
      reactions: [],
      attachments: [],
    },
    {
      id: 'message-3',
      channelId: 'channel-campfire',
      author: { id: 'account-ren', displayName: 'Ren', initials: 'RE', status: 'idle' },
      availability: 'plaintext',
      content: 'Ping me once, not once per message. The new follow mode is exactly what I wanted.',
      createdAt: '2026-06-29T19:27:00.000Z',
      editedAt: null,
      reactions: [{ emoji: '＋1', count: 3, reacted: false }],
      attachments: [],
    },
  ],
  attention: [
    {
      id: 'attention-1',
      kind: 'mention',
      title: 'Mara mentioned you',
      detail: 'campfire · practice run at 8:30',
      createdAt: '2026-06-29T19:12:00.000Z',
      unread: true,
    },
    {
      id: 'attention-2',
      kind: 'followed',
      title: 'Loadout thread updated',
      detail: '2 useful replies since your last visit',
      createdAt: '2026-06-29T18:42:00.000Z',
      unread: false,
    },
  ],
};
